config/routes.rb
Rails.application.routes.draw do
  resources :players, only: [:index, :show, :new, :create, :destroy] do
    resources :api_keys, only: [:new, :create, :show, :destroy] do
      member do
        post "import"
      end
    end
    resources :pilots, only: [:show] do
      member do
        get "import_skills"
        patch "mark_prime"
        patch "make_generic"
        patch "make_fc"
        patch "make_admin"
      end
    end
  end

  resources :api_keys, only: [:index]

  resources :fittings, only: [:index, :show, :new, :create]
  resources :doctrines, only: [:index, :show, :new, :create, :edit, :update]

  get    'login'   => 'sessions#new'
  delete 'logout'  => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create'
end

app/models/pilot.rb
class Pilot < ActiveRecord::Base
  belongs_to :api_key
  has_many :pilot_skills, dependent: :delete_all
  enum access_level: [:generic, :fc, :admin]

  def player
    api_key.player
  end
end

app/controllers/pilots_controller.rb
class PilotsController < ApplicationController
  before_action :logged_in_admin

  def show
    @pilot = Pilot.find(params[:id])
    skills = PilotSkill.includes(skill: :group).where(pilot: @pilot)
    @skills = skills.sort_by { |s| [s.skill.group.name, s.skill.name] }
  end

  def import_skills
    pilot = Pilot.find(params[:id])
    SkillImportJob.perform_later(pilot)
    redirect_to player_pilot_path(pilot.player, pilot)
  end

  def mark_prime
    pilot = Pilot.find(params[:id])
    pilot.toggle!(:prime)
    redirect_to player_pilot_path(pilot.player, pilot)
  end

  def make_generic
    pilot = Pilot.find_by(id: params[:id])
    pilot.generic!
    redirect_to player_pilot_path(pilot.player, pilot)
  end

  def make_fc
    pilot = Pilot.find_by(id: params[:id])
    pilot.fc!
    redirect_to player_pilot_path(pilot.player, pilot)
  end

  def make_admin
    pilot = Pilot.find_by(id: params[:id])
    pilot.admin!
    redirect_to player_pilot_path(pilot.player, pilot)
  end
end

app/views/pilots/show.html.slim
h1
  | Pilot—#{@pilot.name}
  - if @pilot.prime?
    span.prime Prime
= link_to "Toggle Prime", mark_prime_player_pilot_path(@pilot.player, @pilot), \
  method: :patch

dl
  dt Access Level
  dd
    = @pilot.access_level.upcase
    br
    - unless @pilot.access_level == 'generic'
      = link_to "make Generic", make_generic_player_pilot_path(@pilot.player,\
        @pilot), method: :patch
      br
    - unless @pilot.access_level == 'fc'
      = link_to "make FC", make_fc_player_pilot_path(@pilot.player, @pilot),\
        method: :patch
      br
    - unless @pilot.access_level == 'admin'
      = link_to "make Admin", make_admin_player_pilot_path(@pilot.player, \
        @pilot), method: :patch

h2 Skills

p Skills last imported #{time_ago_in_words(@pilot.updated_at)} ago
= link_to "Import player skills", import_skills_player_pilot_path(@pilot.player, @pilot)

table
  thead
    tr
      th Group
      th Skill
      th Level
  tbody
    - @skills.each do |skill|
      tr
        td = skill.skill.group.name
        td = skill.skill.name
        td = skill.level