config/routes.rb
Rails.application.routes.draw do
  resources :players, only: [:index, :show, :new, :create, :destroy] do
    resources :api_keys, only: [:new, :create, :show, :destroy] do
      member do
        post "import"
      end
    end
    resources :pilots, only: [:show] do
      member do
        get "import_skills"
        patch "mark_prime"
        patch "make_generic"
        patch "make_fc"
        patch "make_admin"
      end
    end
  end

  resources :api_keys, only: [:index]

  resources :fittings, only: [:index, :show, :new, :create]
  resources :doctrines, only: [:index, :show, :new, :create, :edit, :update]

  get    'login'   => 'sessions#new'
  delete 'logout'  => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create'
end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  belongs_to :player
  has_many :pilots, dependent: :destroy
  enum status: [:correct, :incorrect, :expired, :no_access]

  def status_text
    case status
    when "correct" then "valid"
    when "incorrect" then "invalid"
    else status
    end
  end
end

app/controllers/api_keys_controller.rb
class ApiKeysController < ApplicationController
  before_action :logged_in_admin

  def index
    @players = Player.includes(:api_keys).order(:name)
  end

  def show
    @player = Player.find(params[:player_id])
    @api_key = ApiKey.find(params[:id])

    characters = EveAPI.new(@api_key).characters
    character_ids = @player.pilots.pluck(:character_id)
    @characters = characters.delete_if { |char|
      character_ids.include?(char.characterID)
    }
  end

  def new
    @player = Player.find(params[:player_id])
    @api_key = @player.api_keys.build
  end

  def create
    @player = Player.find(params[:player_id])
    @api_key = @player.api_keys.build(api_key_params)
    if @api_key.save
      flash[:success] = "API key has been added."
      redirect_to player_path(@player)
    else
      flash[:error] = "API key was not added!"
      render :new
    end
  end

  def import
    @player = Player.find(params[:player_id])
    @api_key = ApiKey.find(params[:id])
    selected_characters = import_params
    selected_characters.each do |character|
      id, name = character.split("|")
      @api_key.pilots.where(character_id: id, name: name).first_or_create
    end
    redirect_to player_path(@player)
  end

  def destroy
    api_key = ApiKey.find(params[:id])
    api_key.destroy
    flash[:success] = "API Key has been deleted."
    redirect_to api_keys_path
  end

  private

  def api_key_params
    params.require(:api_key).permit(:key_id, :v_code)
  end

  def import_params
    return [] unless params[:character]
    params[:character][:id_name]
  end
end

app/views/api_keys/index.html.slim
h1 API Keys

p Please note, when deleting an API Key, you will delete the associated pilots
  and pilot skills imported with that key.

table.not-fixed
  thead
    tr
      th Player
      th Key ID
      th VCode
      th Status
      th Options
  tbody
    - @players.each do |player|
      - if player.api_keys.size > 0
        tr
          td rowspan=player.api_keys.size = link_to player.name, player
          td class=player.api_keys.first.status = player.api_keys.first.key_id
          td class=player.api_keys.first.status = player.api_keys.first.v_code
          td class=player.api_keys.first.status = player.api_keys.first.status_text.capitalize
          td = link_to "✖", player_api_key_path(player, player.api_keys.first), \
                            method: :delete, \
                            data: { confirm: "Are you sure you wish to delete this api key?" }
        - player.api_keys[1..-1].each do |api_key|
          tr
            td class=api_key.status = api_key.key_id
            td class=api_key.status = api_key.v_code
            td class=api_key.status = api_key.status_text.capitalize
            td = link_to "✖", player_api_key_path(player, api_key), \
                              method: :delete, \
                              data: { confirm: "Are you sure you wish to delete this api key?" }

app/views/api_keys/new.html.slim
h1 API keys

= link_to "Get key from EVE", "https://support.eveonline.com/api/Key/CreatePredefined/8"

= simple_form_for [@player, @api_key] do |f|
  = f.input :key_id
  = f.input :v_code
  = f.button :submit

app/views/api_keys/show.html.slim
h1 API Key—#{@player.name}

- if @api_key.incorrect?
  p.flash-error This API Key is invalid.

- if @api_key.expired?
  p.flash-error This API Key is expired.

= form_tag(import_player_api_key_path(@player, @api_key), method: :post)
  ul
    - @characters.each do |character|
      li
        label
          = check_box_tag "character[id_name][]", "#{character.characterID}|#{character.name}"
          = character.name
  = submit_tag "Import Characters"