config/routes.rb
Rails.application.routes.draw do
  resources :players, only: [:index, :show, :new, :create, :destroy] do
    resources :api_keys, only: [:new, :create, :show, :destroy] do
      member do
        post "import"
      end
    end
    resources :pilots, only: [:show] do
      member do
        get "import_skills"
        patch "mark_prime"
        patch "make_generic"
        patch "make_fc"
        patch "make_admin"
      end
    end
  end

  resources :api_keys, only: [:index]

  resources :fittings, only: [:index, :show, :new, :create]
  resources :doctrines, only: [:index, :show, :new, :create, :edit, :update]

  get    'login'   => 'sessions#new'
  delete 'logout'  => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create'
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :api_keys, dependent: :destroy
  has_many :pilots, through: :api_keys
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :logged_in_admin

  def index
    @players = Player.includes(:pilots).order(:name)
  end

  def show
    @player = Player.find(params[:id])
    @pilots = @player.pilots
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      flash[:success] = "New player has been added."
      redirect_to players_path
    else
      flash[:error] = "Player has not been added!"
      render :new
    end
  end

  def destroy
    player = Player.find(params[:id])
    player.destroy
    flash[:success] = "Player has been removed."
    redirect_to players_path
  end

  private

  def player_params
    params.require(:player).permit(:name)
  end
end

app/views/players/index.html.slim
h1 Players

= link_to "Add new player", new_player_path, class: "button"
table
  thead
    tr
      th Player
      th Pilots
      th Access Level
  tbody
    - @players.each do |player|
      tr
        td rowspan=player.pilots.size = link_to player.name, player
        - pilots = player.pilots.sort_by { |p| p.name }
        - if !pilots.empty?
          td
            - if pilots.first.prime?
              span.prime P
            = link_to pilots.first.name, player_pilot_path(player, pilots.first)
          td = pilots.first.access_level.upcase

          - pilots[1..-1].each do |pilot|
            tr
              td
                - if pilot.prime?
                  span.prime P
                = link_to pilot.name, player_pilot_path(player, pilot)
              td = pilot.access_level.upcase
        - else
          td
          td

app/views/players/new.html.slim
h1 Players—Add New

= simple_form_for @player do |f|
  = f.input :name
  = f.button :submit

app/views/players/show.html.slim
h1 Players—#{@player.name}

h2 Pilots
ul.default
  - @pilots.each do |pilot|
    li = link_to pilot.name, player_pilot_path(@player, pilot)

h2 API Keys
= link_to "Add API key", new_player_api_key_path(@player), class: "button"
ul.default
  - @player.api_keys.each do |api_key|
    li = link_to api_key.key_id, [@player, api_key]


= link_to "Remove Player", player_path(@player), \
                           class: "error button", \
                           method: :delete, \
                           data: { confirm: "Are you sure you wish to delete this api key?" }