config/routes.rb
Rails.application.routes.draw do
  resources :players, only: [:index, :show, :new, :create, :destroy] do
    resources :api_keys, only: [:new, :create, :show, :destroy] do
      member do
        post "import"
      end
    end
    resources :pilots, only: [:show] do
      member do
        get "import_skills"
        patch "mark_prime"
        patch "make_generic"
        patch "make_fc"
        patch "make_admin"
      end
    end
  end

  resources :api_keys, only: [:index]

  resources :fittings, only: [:index, :show, :new, :create]
  resources :doctrines, only: [:index, :show, :new, :create, :edit, :update]

  get    'login'   => 'sessions#new'
  delete 'logout'  => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#create'
end

app/views/layouts/_header.html.slim
header
  ul.horizontal
    - if logged_in?
      - if logged_in_as_admin?
        li = link_to "Players", players_path
        li = link_to "API Keys", api_keys_path
      li = link_to "Fittings", fittings_path
      li = link_to "Doctrines", doctrines_path
      li = link_to "Log out", logout_path, method: :delete
    - else
      li = link_to "Login", login_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    title Doctrinator
    meta name="viewport" content="width=device-width, initial-scale=1"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/header'
    section
      - flash.each do |message_type, message|
        div class="flash-#{message_type}" = message
      == yield